INSERT into CREEP values('Aarakocra');
INSERT into CREEP values('Aboleth');
INSERT into CREEP values('Angels');
INSERT into CREEP values('Animated Objects');
INSERT into CREEP values('Ankheg');
INSERT into CREEP values('Azer');
INSERT into CREEP values('Banshee');
INSERT into CREEP values('Basilisk');
INSERT into CREEP values('Behir');
INSERT into CREEP values('Beholders');
INSERT into CREEP values('Blights');
INSERT into CREEP values('Bugbears');
INSERT into CREEP values('Bulette');
INSERT into CREEP values('Bullywug');
INSERT into CREEP values('Cambion');
INSERT into CREEP values('Carrion Crawler');
INSERT into CREEP values('Centaur');
INSERT into CREEP values('Chimera');
INSERT into CREEP values('Chuul');
INSERT into CREEP values('Cloaker');
INSERT into CREEP values('Cockatrice');
INSERT into CREEP values('Couatl');
INSERT into CREEP values('Crawling Claw');
INSERT into CREEP values('Cyclops');
INSERT into CREEP values('Darkmantle');
INSERT into CREEP values('Death Knight');
INSERT into CREEP values('Demilich');
INSERT into CREEP values('Demons');
INSERT into CREEP values('Devils');
INSERT into CREEP values('Dinosaurs');
INSERT into CREEP values('Displacer Beast');
INSERT into CREEP values('Doppelganger');
INSERT into CREEP values('Dragon, Shadow');
INSERT into CREEP values('Dragons');
INSERT into CREEP values('Dragon Turtle');
INSERT into CREEP values('Drider');
INSERT into CREEP values('Dryad');
INSERT into CREEP values('Duergar');
INSERT into CREEP values('Elementals');
INSERT into CREEP values('Elves: Drow');
INSERT into CREEP values('Empyrean');
INSERT into CREEP values('Ettercap');
INSERT into CREEP values('Ettin');
INSERT into CREEP values('Faerie Dragon');
INSERT into CREEP values('Flameskull');
INSERT into CREEP values('Flumph');
INSERT into CREEP values('Fomorian');
INSERT into CREEP values('Fungi');
INSERT into CREEP values('Galeb Duhr');
INSERT into CREEP values('Gargoyle');
INSERT into CREEP values('Genies');
INSERT into CREEP values('Ghost');
INSERT into CREEP values('Ghouls');
INSERT into CREEP values('Giants');
INSERT into CREEP values('Gibbering Mouther');
INSERT into CREEP values('Gith');
INSERT into CREEP values('Gnolls');
INSERT into CREEP values('Gnome, Deep (Svirfneblin)');
INSERT into CREEP values('Goblins');
INSERT into CREEP values('Golems');
INSERT into CREEP values('Gorgon');
INSERT into CREEP values('Grell');
INSERT into CREEP values('Grick');
INSERT into CREEP values('Griffon');
INSERT into CREEP values('Grimlock');
INSERT into CREEP values('Hags');
INSERT into CREEP values('Half-Dragon');
INSERT into CREEP values('Harpy');
INSERT into CREEP values('Hell Hound');
INSERT into CREEP values('Helmed Horror');
INSERT into CREEP values('Hippogriff');
INSERT into CREEP values('Hobgoblins');
INSERT into CREEP values('Homunculus');
INSERT into CREEP values('Hook Horror');
INSERT into CREEP values('Hydra');
INSERT into CREEP values('Intellect Devourer');
INSERT into CREEP values('Invisible Stalker');
INSERT into CREEP values('Jackalwere');
INSERT into CREEP values('Kenku');
INSERT into CREEP values('Kobolds');
INSERT into CREEP values('Kraken');
INSERT into CREEP values('Kuo-toa');
INSERT into CREEP values('Lamia');
INSERT into CREEP values('Lich');
INSERT into CREEP values('Lizardfolk');
INSERT into CREEP values('Lycanthropes');
INSERT into CREEP values('Magmin');
INSERT into CREEP values('Manticore');
INSERT into CREEP values('Medusa');
INSERT into CREEP values('Mephits');
INSERT into CREEP values('Merfolk');
INSERT into CREEP values('Merrow');
INSERT into CREEP values('Mimic');
INSERT into CREEP values('Mind Flayer');
INSERT into CREEP values('Minotaur');
INSERT into CREEP values('Modrons');
INSERT into CREEP values('Mummies');
INSERT into CREEP values('Myconids');
INSERT into CREEP values('Nagas');
INSERT into CREEP values('Nightmare');
INSERT into CREEP values('Nothic');
INSERT into CREEP values('Ogres');
INSERT into CREEP values('Oni');
INSERT into CREEP values('Oozes');
INSERT into CREEP values('Orcs');
INSERT into CREEP values('Otyugh');
INSERT into CREEP values('Owlbear');
INSERT into CREEP values('Pegasus');
INSERT into CREEP values('Peryton');
INSERT into CREEP values('Piercer');
INSERT into CREEP values('Pixie');
INSERT into CREEP values('Pseudodragon');
INSERT into CREEP values('Purple Worm');
INSERT into CREEP values('Quaggoth');
INSERT into CREEP values('Rakshasa');
INSERT into CREEP values('Remorhazes');
INSERT into CREEP values('Revenant');
INSERT into CREEP values('Roc');
INSERT into CREEP values('Roper');
INSERT into CREEP values('Rust Monster');
INSERT into CREEP values('Sahuagin');
INSERT into CREEP values('Salamanders');
INSERT into CREEP values('Satyr');
INSERT into CREEP values('Scarecrow');
INSERT into CREEP values('Shadow');
INSERT into CREEP values('Shambling Mound');
INSERT into CREEP values('Shield Guardian');
INSERT into CREEP values('Skeletons');
INSERT into CREEP values('Slaadi');
INSERT into CREEP values('Specter');
INSERT into CREEP values('Sphinxes');
INSERT into CREEP values('Sprite');
INSERT into CREEP values('Stirge');
INSERT into CREEP values('Succubus/Incubus');
INSERT into CREEP values('Tarrasque');
INSERT into CREEP values('Thri-kreen');
INSERT into CREEP values('Treant');
INSERT into CREEP values('Troglodyte');
INSERT into CREEP values('Troll');
INSERT into CREEP values('Umber Hulk');
INSERT into CREEP values('Unicorn');
INSERT into CREEP values('Vampires');
INSERT into CREEP values('Water Weird');
INSERT into CREEP values('Wight');
INSERT into CREEP values('Will-o-wisp');
INSERT into CREEP values('Wraith');
INSERT into CREEP values('Wyvern');
INSERT into CREEP values('Xorn');
INSERT into CREEP values('Yetis');
INSERT into CREEP values('Yuan-ti');
INSERT into CREEP values('Yugoloths');
INSERT into CREEP values('Zombies');
INSERT into CREEP values('Ape');
INSERT into CREEP values('Awakened Shrub');
INSERT into CREEP values('Awakened Tree');
INSERT into CREEP values('Axe Beak');
INSERT into CREEP values('Baboon');
INSERT into CREEP values('Badger');
INSERT into CREEP values('Bat');
INSERT into CREEP values('Black Bear');
INSERT into CREEP values('Blink Dog');
INSERT into CREEP values('Blood Hawk');
INSERT into CREEP values('Boar');
INSERT into CREEP values('Brown Bear');
INSERT into CREEP values('Camel');
INSERT into CREEP values('Cat');
INSERT into CREEP values('Constrictor Snake');
INSERT into CREEP values('Crab');
INSERT into CREEP values('Crocodile');
INSERT into CREEP values('Death Dog');
INSERT into CREEP values('Deer');
INSERT into CREEP values('Dire Wolf');
INSERT into CREEP values('Draft Horse');
INSERT into CREEP values('Eagle');
INSERT into CREEP values('Elephant');
INSERT into CREEP values('Elk');
INSERT into CREEP values('Flying Snake');
INSERT into CREEP values('Frog');
INSERT into CREEP values('Giant Ape');
INSERT into CREEP values('Giant Badger');
INSERT into CREEP values('Giant Bat');
INSERT into CREEP values('Giant Boar');
INSERT into CREEP values('Giant Centipede');
INSERT into CREEP values('Giant Constrictor Snake');
INSERT into CREEP values('Giant Crab');
INSERT into CREEP values('Giant Crocodile');
INSERT into CREEP values('Giant Eagle');
INSERT into CREEP values('Giant Elk');
INSERT into CREEP values('Giant Fire Beetle');
INSERT into CREEP values('Giant Frog');
INSERT into CREEP values('Giant Goat');
INSERT into CREEP values('Giant Hyena');
INSERT into CREEP values('Giant Lizard');
INSERT into CREEP values('Giant Octopus');
INSERT into CREEP values('Giant Owl');
INSERT into CREEP values('Giant POisonous Snake');
INSERT into CREEP values('Giant Rat');
INSERT into CREEP values('Giant Scorpian');
INSERT into CREEP values('Giant Sea Horse');
INSERT into CREEP values('Giant Shark');
INSERT into CREEP values('Giant Spider');
INSERT into CREEP values('Giant Toad');
INSERT into CREEP values('Giant Vulture');
INSERT into CREEP values('Giant Wasp');
INSERT into CREEP values('Giant Weasel');
INSERT into CREEP values('Giant Wolf Spider');
INSERT into CREEP values('Goat');
INSERT into CREEP values('Hawk');
INSERT into CREEP values('Hunter Shark');
INSERT into CREEP values('Hyena');
INSERT into CREEP values('Jackal');
INSERT into CREEP values('Killer Whale');
INSERT into CREEP values('Lion');
INSERT into CREEP values('Lizard');
INSERT into CREEP values('Mammoth');
INSERT into CREEP values('Mastiff');
INSERT into CREEP values('Mule');
INSERT into CREEP values('Octopus');
INSERT into CREEP values('Owl');
INSERT into CREEP values('Panther');
INSERT into CREEP values('Phase Spider');
INSERT into CREEP values('Poisonous Snake');
INSERT into CREEP values('Polar Bear');
INSERT into CREEP values('Pony');
INSERT into CREEP values('Quipper');
INSERT into CREEP values('Rat');
INSERT into CREEP values('Raven');
INSERT into CREEP values('Reef Shark');
INSERT into CREEP values('Rhinoceros');
INSERT into CREEP values('Riding Horse');
INSERT into CREEP values('Saber-Toothed Tiger');
INSERT into CREEP values('Scorpian');
INSERT into CREEP values('Sea Horse');
INSERT into CREEP values('Spider');
INSERT into CREEP values('Swarm of Bats');
INSERT into CREEP values('Swarm of Insects');
INSERT into CREEP values('Swarm of Poisonous Snakes');
INSERT into CREEP values('Swarm of Quippers');
INSERT into CREEP values('Swarm of Rats');
INSERT into CREEP values('Tiger');
INSERT into CREEP values('Swarm of Ravens');
INSERT into CREEP values('Vulture');
INSERT into CREEP values('Warhorse');
INSERT into CREEP values('Weasel');
INSERT into CREEP values('Winter Wolf');
INSERT into CREEP values('Wolf');
INSERT into CREEP values('Worg');
INSERT into CREEP values('Acolyte');
INSERT into CREEP values('Archmage');
INSERT into CREEP values('Assassin');
INSERT into CREEP values('Bandit');
INSERT into CREEP values('Bandit Captain');
INSERT into CREEP values('Berserker');
INSERT into CREEP values('Commoner');
INSERT into CREEP values('Cultist');
INSERT into CREEP values('Cult Fanatic');
INSERT into CREEP values('Druid');
INSERT into CREEP values('Gladiator');
INSERT into CREEP values('Guard');
INSERT into CREEP values('Knight');
INSERT into CREEP values('Mage');
INSERT into CREEP values('Noble');
INSERT into CREEP values('Priest');
INSERT into CREEP values('Scout');
INSERT into CREEP values('Spy');
INSERT into CREEP values('Thug');
INSERT into CREEP values('Tribal Warrior');
INSERT into CREEP values('Veteran');
