begin

insert into DD_ITEM ([Name]) values ('Club');
insert into DD_ITEM ([Name]) values ('Greatclub');
insert into DD_ITEM ([Name]) values ('Handaxe');
insert into DD_ITEM ([Name]) values ('Javelin');
insert into DD_ITEM ([Name]) values ('Light hammer');
insert into DD_ITEM ([Name]) values ('Mace');
insert into DD_ITEM ([Name]) values ('Quarterstaff');
insert into DD_ITEM ([Name]) values ('Sickle');
insert into DD_ITEM ([Name]) values ('Spear');
insert into DD_ITEM ([Name]) values ('Crossbow, light');
insert into DD_ITEM ([Name]) values ('Dart');
insert into DD_ITEM ([Name]) values ('Shortbow');
insert into DD_ITEM ([Name]) values ('Sling');
insert into DD_ITEM ([Name]) values ('Battleaxe');
insert into DD_ITEM ([Name]) values ('Flail');
insert into DD_ITEM ([Name]) values ('Glaive');
insert into DD_ITEM ([Name]) values ('Greataxe');
insert into DD_ITEM ([Name]) values ('Greatsword');
insert into DD_ITEM ([Name]) values ('Halberd');
insert into DD_ITEM ([Name]) values ('Lance');
insert into DD_ITEM ([Name]) values ('Longsword');
insert into DD_ITEM ([Name]) values ('Maul');
insert into DD_ITEM ([Name]) values ('Morningstar');
insert into DD_ITEM ([Name]) values ('Pike');
insert into DD_ITEM ([Name]) values ('Rapier');
insert into DD_ITEM ([Name]) values ('Scimitar');
insert into DD_ITEM ([Name]) values ('Shortsword');
insert into DD_ITEM ([Name]) values ('Trident');
insert into DD_ITEM ([Name]) values ('War pick');
insert into DD_ITEM ([Name]) values ('Warhammer');
insert into DD_ITEM ([Name]) values ('Whip');
insert into DD_ITEM ([Name]) values ('Blowgun');
insert into DD_ITEM ([Name]) values ('Crossbow, hand');
insert into DD_ITEM ([Name]) values ('Crossbow, heavy');
insert into DD_ITEM ([Name]) values ('Longbow');
insert into DD_ITEM ([Name]) values ('Net');
insert into DD_ITEM ([Name]) values ('Abacus');
insert into DD_ITEM ([Name]) values ('Acid (vial)');
insert into DD_ITEM ([Name]) values ('Alchemists Fire (flask)');
insert into DD_ITEM ([Name]) values ('Arrows');
insert into DD_ITEM ([Name]) values ('Blowgun Needles');
insert into DD_ITEM ([Name]) values ('Crossbow bolts');
insert into DD_ITEM ([Name]) values ('Sling bullets');
insert into DD_ITEM ([Name]) values ('Antitoxin (vial)');
insert into DD_ITEM ([Name]) values ('Crystal');
insert into DD_ITEM ([Name]) values ('Orb');
insert into DD_ITEM ([Name]) values ('Rod');
insert into DD_ITEM ([Name]) values ('Staff');
insert into DD_ITEM ([Name]) values ('Wand');
insert into DD_ITEM ([Name]) values ('Backpack');
insert into DD_ITEM ([Name]) values ('Ball bearings');
insert into DD_ITEM ([Name]) values ('Barrel');
insert into DD_ITEM ([Name]) values ('Basket');
insert into DD_ITEM ([Name]) values ('Bedroll');
insert into DD_ITEM ([Name]) values ('Bell');
insert into DD_ITEM ([Name]) values ('Blanket');
insert into DD_ITEM ([Name]) values ('Block and tackle');
insert into DD_ITEM ([Name]) values ('Book');
insert into DD_ITEM ([Name]) values ('Bottle, glass');
insert into DD_ITEM ([Name]) values ('Bucket');
insert into DD_ITEM ([Name]) values ('Caltrops');
insert into DD_ITEM ([Name]) values ('Candle');
insert into DD_ITEM ([Name]) values ('Case, crossbow bolt');
insert into DD_ITEM ([Name]) values ('Case, map or scroll');
insert into DD_ITEM ([Name]) values ('Chain');
insert into DD_ITEM ([Name]) values ('Chalk');
insert into DD_ITEM ([Name]) values ('Chest');
insert into DD_ITEM ([Name]) values ('Climbers Kit');
insert into DD_ITEM ([Name]) values ('Clothes, common');
insert into DD_ITEM ([Name]) values ('Clothes, costume');
insert into DD_ITEM ([Name]) values ('Clothes, fine');
insert into DD_ITEM ([Name]) values ('Clothes, travelers');
insert into DD_ITEM ([Name]) values ('Component Pouch');
insert into DD_ITEM ([Name]) values ('Crowbar');
insert into DD_ITEM ([Name]) values ('Sprig of mistletoe');
insert into DD_ITEM ([Name]) values ('Totem');
insert into DD_ITEM ([Name]) values ('Wooden Staff');
insert into DD_ITEM ([Name]) values ('Yew wand');
insert into DD_ITEM ([Name]) values ('Fishing Tackle');
insert into DD_ITEM ([Name]) values ('Flask or tankard');
insert into DD_ITEM ([Name]) values ('Grappling Hook');
insert into DD_ITEM ([Name]) values ('Hammer');
insert into DD_ITEM ([Name]) values ('Hammer, sledge');
insert into DD_ITEM ([Name]) values ('Healers kit');
insert into DD_ITEM ([Name]) values ('Amulet');
insert into DD_ITEM ([Name]) values ('Emblem');
insert into DD_ITEM ([Name]) values ('Reliquary');
insert into DD_ITEM ([Name]) values ('Holy water (flask)');
insert into DD_ITEM ([Name]) values ('Hourglass');
insert into DD_ITEM ([Name]) values ('Hunting trap');
insert into DD_ITEM ([Name]) values ('Ink (1 once bottle)');
insert into DD_ITEM ([Name]) values ('Ink Pen');
insert into DD_ITEM ([Name]) values ('Jug or pitcher');
insert into DD_ITEM ([Name]) values ('Ladder (10-foot)');
insert into DD_ITEM ([Name]) values ('Lamp');
insert into DD_ITEM ([Name]) values ('Lantern, bullseye');
insert into DD_ITEM ([Name]) values ('Lantern, hooded');
insert into DD_ITEM ([Name]) values ('Lock');
insert into DD_ITEM ([Name]) values ('Magnifying Glass');
insert into DD_ITEM ([Name]) values ('Manacles');
insert into DD_ITEM ([Name]) values ('Mess kit');
insert into DD_ITEM ([Name]) values ('Mirror, steel');
insert into DD_ITEM ([Name]) values ('Oil, flask');
insert into DD_ITEM ([Name]) values ('Paper (one sheet)');
insert into DD_ITEM ([Name]) values ('Perfume (vial)');
insert into DD_ITEM ([Name]) values ('Pick, miners');
insert into DD_ITEM ([Name]) values ('Piton');
insert into DD_ITEM ([Name]) values ('Poison, basic (vial)');
insert into DD_ITEM ([Name]) values ('Pole (10 foot)');
insert into DD_ITEM ([Name]) values ('Pot, iron');
insert into DD_ITEM ([Name]) values ('Potion of Healing');
insert into DD_ITEM ([Name]) values ('Pouch');
insert into DD_ITEM ([Name]) values ('Quiver');
insert into DD_ITEM ([Name]) values ('Ram, Portable');
insert into DD_ITEM ([Name]) values ('Rations (1 day)');
insert into DD_ITEM ([Name]) values ('Robes');
insert into DD_ITEM ([Name]) values ('Rope, hempen (50 feet)');
insert into DD_ITEM ([Name]) values ('Rope, silk (50 feet)');
insert into DD_ITEM ([Name]) values ('Slack');
insert into DD_ITEM ([Name]) values ('Scale, merchants');
insert into DD_ITEM ([Name]) values ('Sealing wax');
insert into DD_ITEM ([Name]) values ('Shovel');
insert into DD_ITEM ([Name]) values ('Signal whistle');
insert into DD_ITEM ([Name]) values ('Signet ring');
insert into DD_ITEM ([Name]) values ('Soap');
insert into DD_ITEM ([Name]) values ('Spellbook');
insert into DD_ITEM ([Name]) values ('Spikes, iron (10)');
insert into DD_ITEM ([Name]) values ('Spyglass');
insert into DD_ITEM ([Name]) values ('Ten, two-person');
insert into DD_ITEM ([Name]) values ('Tinderbox');
insert into DD_ITEM ([Name]) values ('Torch');
insert into DD_ITEM ([Name]) values ('Vial');
insert into DD_ITEM ([Name]) values ('Waterskin');
insert into DD_ITEM ([Name]) values ('Whetstone');


insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blade Ward', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dancing Lights', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Friends', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Light', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mage Hand', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mending', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Message', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Minor Illusion', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Prestidigitation', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Strike', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Vicious Mockery', '2', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animal Friendship', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Bane', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Charm Person', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Comprehend Languages', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cure Wounds', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Magic', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Disguise Self', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dissonant Whispers', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Faerie Fire', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feather Fall', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Healing Word', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Heroism', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Identify', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Illusory Script', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Longstrider', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Silent Image', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sleep', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Speak with Animals', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tashas Hideous Laughter', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Thunderwave', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Unseen Servant', '2', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animal Messenger', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blindness/Deafness', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Calm Emotions', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cloud of Daggers', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Crown of Madness', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Thoughts', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Enhance Ability', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Enthrall', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Heat Metal', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Person', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Invisibility', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Knock', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Lesser Restoration', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Animals or Plants', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Object', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Mouth', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Phantasmal Force', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('See Invisibility', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shatter', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Silence', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Suggestion', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Zone of Truth', '2', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Bestow Curse', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Clairvoyance', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dispel Magic', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fear', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feign Death', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Glyph of Warding', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hypnotic Pattern', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Leomunds Tiny Hut', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Major Image', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Nondetection', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Plant Growth', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sending', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Speak with Dead', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Speak with Plants', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stinking Cloud', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tongues', '2', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Compulsion', '2', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Confusion', '2', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dimension Door', '2', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Freedom of Movement', '2', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Greater Invisibility', '2', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hallucinatory Terrain', '2', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Creature', '2', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Polymorph', '2', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animate Objects', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Awaken', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dominate Person', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dream', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Geas', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Greater Restoration', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Monster', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Legend Lore', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mass Cure Wounds', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mislead', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Modify Memory', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Planar Binding', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Raise Dead', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Scrying', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Seeming', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Teleportation Circle', '2', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Eyebite', '2', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Find the Path', '2', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Guards and Wards', '2', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mass Suggestion', '2', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ottos Irresistible Dance', '2', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Programmed Illusion', '2', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Seeing', '2', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Etherealness', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Forcecage', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mirage Arcane', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mordenkainens Magnificent Mansion', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Modenkainens Sword', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Project Image', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Regenerate', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Resurrection', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Symbol', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Teleport', '2', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dominate Monster', '2', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feeblemind', '2', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Glibness', '2', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mind Blank', '2', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Power Word Stun', '2', '8');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Foresight', '2', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Power Word Heal', '2', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Power Word Kill', '2', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Polymorph', '2', '9');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Guidance', '3', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Light', '3', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mending', '3', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Resistence', '3', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sacred Flame', '3', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Spare the Dying', '3', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Thaumaturgy', '3', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Bane', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Bless', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Command', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Create of Destroy Water', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cure Wounds', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Evil and Good', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Magic', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Poison and Disease', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Guiding Bolt', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Healing Word', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Inflict Wounds', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Evil and Good', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Purify Food and Drink', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sanctuary', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shield of Faith', '3', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Aid', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Augury', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blindness/Deafness', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Calm Emotions', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Continual Flame', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Enhance Ability', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Find Traps', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gentle Repose', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold person', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Lesser Restoration', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Object', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Prayer of Healing', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Poison', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Silence', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Spiritual Weapon', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Warding Bond', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Zone of Truth', '3', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animate Dead', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Beacon of Hope', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Bestow Curse', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Clairvoyance', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Create Food and Water', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Daylight', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dispel Magic', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feign Death', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Glyph of Warding', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Circle', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mass Healing Word', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Meld into Stone', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Energy', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Remove Curse', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Revivify', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sending', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Speak with Dead', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Spirit Guardians', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tongues', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Water Walk', '3', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Banishment', '3', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Control Water', '3', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Death Ward', '3', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Divination', '3', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Freedom of Movement', '3', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Guardian of Faith', '3', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Creature', '3', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stone Shape', '3', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Commune', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Contagion', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dispel Evil and Good', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Flame Strike', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Geas', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Greater Restoration', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hallow', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Insect Plague', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Legend Lore', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mass Cure Wounds', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Planar Binding', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Raise Dead', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Scrying', '3', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blade Barrier', '3', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Create Undead', '3', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Find the Path', '3', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Forbiddence', '3', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Harm', '3', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Heal', '3', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Heroes Feet', '3', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Planar Ally', '3', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Seeing', '3', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Word of Recall', '3', '6');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Celestial', '3', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Divine Word', '3', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Etherealness', '3', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fire Storm', '3', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Plane Shift', '3', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Regenerate', '3', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Resurrection', '3', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Symbol', '3', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Antimage Field', '3', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Control Weather', '3', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Earthquake', '3', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Holy Aura', '3', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Astral Projection', '3', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gate', '3', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mass Heal', '3', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Resurrection', '3', '9');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Druidcraft', '4', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Guidance', '4', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mending', '4', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Poison Spray', '4', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Produce Flame', '4', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Resistance', '4', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shillelagh', '4', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Thorn Whip', '4', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animal Friendship', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Charm Person', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Create of Destroy Water', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cure Wounds', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Magic', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Poison and Disease', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Entangle', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Faerie Fire', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fog Cloud', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Goodberry', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Healing Word', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Jump', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Longstrider', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Purify Food and Drink', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Speak with Animals', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Thunderwave', '4', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animal Messenger', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Barkskin', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Beast Sense', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Darkvision', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Enhance Ability', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Find Traps', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Flame Blade', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Flaming Sphere', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gust of Wind', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Heat Metal', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Person', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Lesser Restoration', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Animals or Plants', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Object', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Moonbeam', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Pass without Trace', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Poison', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Spike Growth', '4', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Call Lightning', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Animals', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Daylight', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dispel Magic', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feign Death', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Meld into Stone', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Plant Growth', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Energy', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sleet Storm', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Speak with Plants', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Water Breathing', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Water Walk', '4', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wind Wall', '4', '3');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blight', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Confusion', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Minor Elementals', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Woodland Beings', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Control Water', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dominate Beast', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Freedom of Movement', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Giant Insect', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Grasping Vine', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hallucinatory Terrain', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ice Storm', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Creature', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Polymorph', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stone Shape', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stoneskin', '4', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wall of Fire', '4', '4');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Antilife SHell', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Awaken', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Commune with Nature', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Elemental', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Contagion', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Geas', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Greater Restoration', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Insect Plague', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mass Cure Wounds', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Planar Binding', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Reincarnate', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Scrying', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tree Stride', '4', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wall of Stone', '4', '5');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Fey', '4', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Find the Path', '4', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Heal', '4', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Heroes Feast', '4', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Move Earth', '4', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sunbeam', '4', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Transport via Plants', '4', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wall of Thorns', '4', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wind Walk', '4', '6');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fire Storm', '4', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mirage Arcane', '4', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Plane Shift', '4', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Regenerate', '4', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Reverse Gravity', '4', '7');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animal Shapes', '4', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Antipathy/Sympathy', '4', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Control Weather', '4', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Earthquake', '4', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feeblemind', '4', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sunburst', '4', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tsunami', '4', '8');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Foresight', '4', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shapechange', '4', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Storm of Vengeance', '4', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Resurrection', '4', '9');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Bless', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Command', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Compelled Duel', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cure Wounds', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Evil and Good', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Magic', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Poison and Disease', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Divine Favor', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Heroism', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Evil and Good', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Purify Food and Drink', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Searing Smite', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shield of Faith', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Thunderous Smithe', '7', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wrathful Smite', '7', '1');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Aid', '7', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Branding Smite', '7', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Find Steed', '7', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Lesser Restoration', '7', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Object', '7', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Weapon', '7', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Poison', '7', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Zone of Truth', '7', '2');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Aura of Vitality', '7', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blinding Smite', '7', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Create Food and Water', '7', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Crusaders Mantle', '7', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Daylight', '7', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dispel Magic', '7', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Elemental Weapon', '7', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Circle', '7', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Remove Curse', '7', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Revivify', '7', '3');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Aura of Life', '7', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Aura of Purity', '7', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Banishment', '7', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Death Ward', '7', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Creature', '7', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Staggering Smite', '7', '4');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Banishing Smite', '7', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Circle of Power', '7', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Destructive Smite', '7', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dispel Evil and Good', '7', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Geas', '7', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Raise Dead', '7', '5');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Alarm', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animal Friendship', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cure Wounds', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Magic', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Poison and Disease', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ensnaring Strike', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fog Cloud', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Goodberry', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hail of Thorns', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hunters Mark', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Jump', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Longstrider', '8', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Speak with Animals', '8', '1');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animal Messenger', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Barkskin', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Beast Sense', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cordon of Arrows', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Darkvision', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Find Traps', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Lesser Restoration', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Animals or Plants', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Object', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Pass without Trace', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Poison', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Silence', '8', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Spike Growth', '8', '2');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Animals', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Barrage', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Daylight', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Lightning Arrow', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Nondetection', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Plant Growth', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Energy', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Speak with Plants', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Water Breathing', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Water Walk', '8', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wind Wall', '8', '3');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Woodland Beings', '8', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Freedom of Movement', '8', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Grasping Vine', '8', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Creature', '8', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stoneskin', '8', '4');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Commune with Nature', '8', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Volley', '8', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Swift Quiver', '8', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tree Stride', '8', '5');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Acid Splash', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blade Ward', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Chill Touch', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dancing Lights', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fire Bolt', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Friends', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Light', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mage Hand', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mending', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Message', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Minor Illusion', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Poison Spray', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Prestidigitation', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ray of Frost', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shocking Grasp', '10', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Strike', '10', '0');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Burning Hands', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Charm Person', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Chromatic Orb', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Color Spray', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Comprehend Languages', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Magic', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Disguise Self', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Expeditious Retreat', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('False Life', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feather Fall', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fog Cloud', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Jump', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mage Armor', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Missle', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ray of Sickness', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shield', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Silent Image', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sleep', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Thunderwave', '10', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Witch Bolt', '10', '1');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Alter Self', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blindness/Deafness', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blur', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cloud of Daggers', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Crown of Madness', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Darkness', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Darkvision', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Thoughts', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Enhance Ability', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Enlarge/Reduce', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gust of Wind', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Person', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Invisibility', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Knock', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Levitate', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mirror Image', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Misty Step', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Phantasmal Force', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Scorching Ray', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('See Invisibility', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shatter', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Spider Climb', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Suggestion', '10', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Web', '10', '2');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blink', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Clairvoyance', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Counterspell', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Daylight', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dispel Magic', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fear', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fireball', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fly', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gaseous Form', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Haste', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hypnotic Pattern', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Lightning Bolt', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Major Image', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Energy', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sleet Storm', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Slow', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stinking Cloud', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tongues', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Water Breathing', '10', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Water Walk', '10', '3');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Banishment', '10', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blight', '10', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Confusion', '10', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dimension Door', '10', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dominate Beast', '10', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Greater Invisibility', '10', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ice Storm', '10', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Polymorph', '10', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stoneskin', '10', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wall of Fire', '10', '4');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animate Objects', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cloudkill', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cone of Cold', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Creation', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dominate Person', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Person', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Monster', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Insect Plague', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Seeming', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Telekinesis', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Teleportation Circle', '10', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wall of Stone', '10', '5');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Arcane Gate', '10', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Chain Lightning', '10', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Circle of Death', '10', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Disintegrate', '10', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Eyebite', '10', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Globe of Invulnerability', '10', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mass Suggestion', '10', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Move Earth', '10', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sunbeam', '10', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Seeing', '10', '6');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Delayed Blast Fireball', '10', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Etherealness', '10', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Finger of Death', '10', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fire Storm', '10', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Plane Shift', '10', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Prismatic Spray', '10', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Reverse Gravity', '10', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Teleport', '10', '7');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dominate Monster', '10', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Earthquake', '10', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Incendiary Cloud', '10', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Power Word Stun', '10', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sunburst', '10', '8');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gate', '10', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Meteor Swarm', '10', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Power Word Kill', '10', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Time Stop', '10', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wish', '10', '9');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blade Ward', '11', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Chill Touch', '11', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Eldritch Blast', '11', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Friends', '11', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mage Hand', '11', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Minor Illusion', '11', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Poison Spray', '11', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Prestidigitation', '11', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Strike', '11', '0');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Armor of Agathys', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Arms of Hadar', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Charm Person', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Comprehend Languages', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Expeditious Retreat', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hellish Rebuke', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hex', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Illusory Script', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Good and Evil', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Unseen Servant', '11', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Witch Bolt', '11', '1');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cloud of Daggers', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Crown of Madness', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Darkness', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Enthrall', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Person', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Invisibility', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mirror Image', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Misty Step', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ray of Enfeeblement', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shatter', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Spider Climb', '11', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Suggestion', '11', '2');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Counterspell', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dispel Magic', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fear', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fly', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gaseous Form', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hunger of Hadar', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hypnotic Pattern', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Circle', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Major Image', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Remove Curse', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tongues', '11', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Vampiric Touch', '11', '3');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Banishment', '11', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blight', '11', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dimension Door', '11', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hallucinatory Terrain', '11', '4');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Contact other Plane', '11', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dream', '11', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Monster', '11', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Scrying', '11', '5');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Arcane Gate', '11', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Circle of Death', '11', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Fey', '11', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Create Undead', '11', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Eyebite', '11', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Flesh to Stone', '11', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mass Suggestion', '11', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Seeing', '11', '6');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Etherealness', '11', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Finger of Death', '11', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Forcecage', '11', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Plane Shift', '11', '7');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Demiplane', '11', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dominate Monster', '11', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feeblemind', '11', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Glibness', '11', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Power Word Stun', '11', '8');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Astral Projection', '11', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Foresight', '11', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Imprisonment', '11', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Power Word Kill', '11', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Polymorph', '11', '9');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Acid Splash', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blade Wand', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Chill Touch', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dancing Lights', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fire Bolt', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Friends', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Light', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mage Hand', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mending', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Message', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Minor Illusion', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Poison Spray', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Prestidigitation', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ray of Frost', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shocking Grasp', '12', '0');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Strike', '12', '0');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Alarm', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Burning Hands', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Charm Person', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Chromatic Orb', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Color Spray', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Comprehend Languages', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Magic', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Disguise Self', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Expeditious Retreat', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('False Life', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feather Fall', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Find Familiar', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fog Cloud', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Grease', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Identify', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Illusory Script', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Jump', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Longstrider', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mage Armor', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Missle', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Evil and Good', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ray of Sickness', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shield', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Silent Image', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sleep', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tashas Hideous Laughter', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tensers Floating Disk', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Thunderwave', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Unseen Servant', '12', '1');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Witch Bolt', '12', '1');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Alter Self', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Arcane Lock', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blindness/Deafness', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blue', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cloud of Daggers', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Continual Flame', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Crown of Madness', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Darkness', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Darkvision', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Detect Thoughts', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Enlarge/Reduce', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Flaming Sphere', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gentle Repose', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gust of Wind', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Person', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Invisibility', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Knock', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Levitate', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Object', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Mouth', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Weapon', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Melfs Acid Arrow', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mirror Image', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Misty Step', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Nystuls Magic Aura', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Phantasmal Force', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ray of Enfeeblement', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Rope Trick', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Scorching Ray', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('See Invisibility', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shatter', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Spider Climb', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Suggestion', '12', '2');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Web', '12', '2');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animate Dead', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Bestow Curse', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blink', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Clairvoyance', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Counterspell', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dispel Magic', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fear', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feign Death', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fireball', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fly', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gaseous Form', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Glyph of Warding', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Haste', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hypnotic Pattern', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Leomunds Tiny Hut', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Lightning Bolt', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Circle', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Nondetection', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Phantom Seed', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Protection from Energy', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Remove Curse', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sending', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sleet Storm', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Slow', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stinking Cloud', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Tongues', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Vampiric Touch', '12', '3');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Water Breathing', '12', '3');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Arcane Eye', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Banishment', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Blight', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Confusion', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Minor Elementals', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Control Water', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dimension Door', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Evards Black Tentacles', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fabricate', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Fire Shield', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Greater Invisibility', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hallucinatory Terrain', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ice Storm', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Leomunds Secret Chest', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Locate Creature', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mordenkainens Faithful Hound', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mordenkainens Private Sanctum', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Otilukes Resilient Sphere', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Phantasmal Killer', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Polymorph', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stone Shape', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Stoneskin', '12', '4');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wall of Fire', '12', '4');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Animate Objects', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Bigbys Hand', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cloudkill', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Cone of Cold', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Conjure Elemental', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Contact Other Plane', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Creation', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dominate Person', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dream', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Geas', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Hold Monster', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Legend Lore', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mislead', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Modify Memory', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Passwall', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Planar Binding', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Rarys Telepathic Bond', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Scrying', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Seeming', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Telekinesis', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Teleportation Circle', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wall of Force', '12', '5');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wall of Stone', '12', '5');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Arcane Gate', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Chain Lightning', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Circle of Death', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Contingency', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Create Undead', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Disintegrate', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Drawmijs Instant Summons', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Eyebite', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Flesh to Stone', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Globe of Invulnerability', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Guards and Wards', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Magic Jar', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mass Suggestion', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Move Earth', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Otilukes Freezing Sphere', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Ottos Irresistible Dance', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Programmed Illusion', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sunbeam', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Seeing', '12', '6');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wall of Ice', '12', '6');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Delayed Blast Fireball', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Etherealness', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Finger of Death', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Forcecage', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mirage Arcane', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mordenkainens Magnificent Mansion', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mordenkainens Sword', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Plane Shift', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Prismatic Spray', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Project Image', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Reverse Gravity', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sequester', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Simulacrum', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Symbol', '12', '7');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Teleport', '12', '7');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Antimagic Field', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Antipathy/Sympathy', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Clone', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Control Weather', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Demiplane', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Dominate Monster', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Feeblemind', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Incendiary Cloud', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Maze', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Mind Blank', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Power Word Stun', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Sunburst', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Telepathy', '12', '8');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Trap the Soul', '12', '8');

insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Astral Projection', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Foresight', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Gate', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Imprisonment', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Meteor Swarm', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Power Word Kill', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Prismatic Wall', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Shapechange', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Time Stop', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('True Polymorph', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Weird', '12', '9');
insert into DD_SPELL ([Name], [ClassID], [RequiredLevel]) values ('Wish', '12', '9');







































end